[Wayland_protocols]
git-tree-sha1 = "6f2b784592cf30d2e4c03873f8cfcb0e05beecf7"

    [[Wayland_protocols.download]]
    sha256 = "93be432a55d7dce9878654367dd1912fba393ca22b3bf81c9e650f3711976f6f"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.44.0+0/Wayland_protocols.v1.44.0.any.tar.gz"
