[Wayland_protocols]
git-tree-sha1 = "0b1f3af59779d821b50ab2a6605fdb669865517d"

    [[Wayland_protocols.download]]
    sha256 = "b0ca713503a3f90e4e7bfdb4fe1c5c55a63a4f15db94b2e2c891c63fa178428f"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.24.0+0/Wayland_protocols.v1.24.0.any.tar.gz"
