[Wayland_protocols]
git-tree-sha1 = "ecf833b19a0819695e6307474b4ded343297e9e6"

    [[Wayland_protocols.download]]
    sha256 = "13a94e156522acf6d02e556795e46531306760be347a8f6d0b77afaacebe7c17"
    url = "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.18.0+3/Wayland_protocols.v1.18.0.any.tar.gz"
