# Autogenerated wrapper script for Wayland_protocols_jll for any
JLLWrappers.@generate_wrapper_header("Wayland_protocols")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
