# Autogenerated wrapper script for Wayland_protocols_jll for any
using Wayland_jll
JLLWrappers.@generate_wrapper_header("Wayland_protocols")
function __init__()
    JLLWrappers.@generate_init_header(Wayland_jll)
    JLLWrappers.@generate_init_footer()
end  # __init__()
